version: "2"

services:
  nginx:
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/ssl-certs:/etc/ssl-certs
    command: |
      "exec nginx -g 'daemon off;'"
